project:
  type: book

book:
  title: "A guide to the single-cell epigenomics analysis"
  author: "Kai Zhang"
  google-analytics: "G-4T647M9GLJ"
  site-url: https://kzhang.org/epigenomcis-analysis/
  repo-url: https://github.com/kaizhang/epigenomics-analysis/
  repo-branch: main
  repo-actions: [edit, issue]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - intro.qmd
    - file_format.qmd
    - dim_reduct.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
  epub:
    cover-image: images/cover.png