project:
  type: book

book:
  title: "Single-cell ATAC-seq analysis pipeline"
  author: "Kai Zhang"
  cover-image: images/cover.png
  google-analytics: "G-4T647M9GLJ"
  site-url: https://kzhang.org/Book-scATAC-seq/
  repo-url: https://github.com/kaizhang/Book-scATAC-seq/
  repo-branch: main
  repo-actions: [edit, issue]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - intro.qmd
    - qc.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport